version: '3.7'

services:
  grafana:
    build:
      context: grafana/
      args:
        GRAFANA_VERSION: $GRAFANA_VERSION
    hostname: grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./data/grafana
        target: /var/lib/grafana
      - type: bind
        source: ./grafana/config/grafana.ini
        target: /etc/grafana/grafana.ini
      - type: bind
        source: ./grafana/dashboards
        target: /etc/grafana/provisioning/dashboards
      - type: bind
        source: ./grafana/datasources
        target: /etc/grafana/provisioning/datasources
    networks:
      - grafana-network

networks:
  grafana-network:
    driver: bridge